test_that("write_biom - errors", {
  expect_error(write_biom("Bad_type"))

  # no file name with nameless dataset
  data <- new_dataset()
  expect_error(write_biom(data))
})

test_that("write_biom", {
  miseq <- miseq_sop_example()

  bin_types <- miseq$get_bin_types()

  file_root <- get_full_name("test-miseq")

  outputs <- c(
    get_full_name("test-miseq.otu.biom"),
    get_full_name("test-miseq.asv.biom"),
    get_full_name("test-miseq.phylotype.biom")
  )

  expect_equal(write_biom(miseq, file_root), outputs)

  # read biom file - otu
  hdata <- rbiom::read_biom(outputs[1])

  expect_equal(hdata$id, "miseq_sop")
  comment <- paste0(
    "Generated by: strollur (v0.1.3)\nMaintainer: Pat ",
    "Schloss <pschloss@umich.edu>\nSource: https://github.",
    "com/mothur/strollur, https://mothur.org/strollur/"
  )
  expect_equal(hdata$id, "miseq_sop")
  expect_equal(hdata$comment, comment)
  expect_equal(hdata$n_otus, count(miseq, type = "bin", bin_type = "otu"))
  expect_equal(hdata$otus, names(miseq, type = "bin", bin_type = "otu"))
  expect_equal(hdata$n_samples, count(miseq, type = "sample"))
  expect_equal(dim(hdata$counts), c(531, 19))
  expect_equal(
    hdata$samples,
    strollur::names(miseq, type = "sample")
  )

  expect_equal(
    hdata$metadata$.sample,
    strollur::names(miseq, type = "sample")
  )
  df <- xdev_report(miseq, type = "sample_assignment")
  expect_equal(as.character(hdata$metadata$Treatment.sample), df$sample)
  expect_equal(as.character(hdata$metadata$Treatment.treatment), df$treatment)

  expect_equal(nrow(hdata$taxonomy), 531)
  expect_equal(ncol(hdata$taxonomy), 7)
  expect_equal(as.character(hdata$taxonomy[[10, "Phylum"]]), "Firmicutes")

  otu1_seq <- paste0(
    "TAC--GT-AG-GGG--GCA-A-G-C-G-T-T--AT-C-CGG-AT--TT-A-C-T",
    "--GG-GT--GT-A-AA-GG-GA-GC-G-TA-GAC-G-G-C-TG-T-G-C-AA-G",
    "-T-C-T-G-A-A-G--TG-A-AA-TG-C-C-GG-GG--CT-C-AA-C-C-C-C-",
    "G-G-A-ACT-G-C-TTTG-GAAAC-TG-T-ACAGC-TAGA-GT-GC-AG-GA-G",
    "-G---GG-T-G-AGCGGAATTCCTAGTGT-AGCGGT-GAAATGCGTAG-AT-A-",
    "TT-AG-GA-GG-AACACCGGT-GGCGAAGGCG------GCTCA-CTG-G-AC-T",
    "G-T-A-ACTGACG-TTGA-GGCT-CGAAA-GCG-TGGGG-AGC-AAACAGG"
  )
  expect_equal(hdata$sequences[[1]], otu1_seq)

  # read biom file - asv
  hdata <- rbiom::read_biom(outputs[2])

  expect_equal(hdata$n_otus, count(miseq, type = "bin", bin_type = "asv"))
  expect_equal(hdata$otus, names(miseq, type = "bin", bin_type = "asv"))
  expect_equal(hdata$n_samples, count(miseq, type = "sample"))
  expect_equal(dim(hdata$counts), c(2425, 19))
  expect_equal(
    hdata$samples,
    strollur::names(miseq, type = "sample")
  )

  expect_equal(nrow(hdata$taxonomy), 2425)
  expect_equal(ncol(hdata$taxonomy), 7)
  expect_equal(
    as.character(hdata$taxonomy[[5, "Phylum"]]),
    "\"Bacteroidetes\""
  )

  asv1_seq <- paste0(
    "TAC--GG-AG-GAT--GCG-A-G-C-G-T-T--AT-C-CGTGAT--TT-A-T-T",
    "--GG-GT--TT-A-AA-GG-GT-GC-G-TA-GGC-G-G-A-CA-G-T-T-AA-G",
    "-T-C-A-G-C-G-G--TA-A-AA-TT-G-A-GA-GG--CT-C-AA-C-C-T-C-",
    "T-T-C--CC-G-C-CGTT-GAAAC-TG-A-TTGTC-TTGA-GT-GG-GC-GA-G-",
    "A---AG-T-A-TGTGGAATGCGTGGTGT-AGCGGT-GAAATGCATAG-AT-A-TC",
    "-AC-GC-AG-AACTCCGAT-TGCGAAGGCA------GCATA-CCG-G-CG-CC-C",
    "-A-ACTGACG-CTGA-AGCA-CGAAA-GCG-TGGGT-ATC-GAACAGG"
  )
  expect_equal(hdata$sequences[[1]], asv1_seq)

  # read biom file - phylotype
  hdata <- rbiom::read_biom(outputs[3])

  expect_equal(hdata$n_otus, count(miseq,
    type = "bin",
    bin_type = "phylotype"
  ))
  expect_equal(hdata$otus, names(miseq, type = "bin", bin_type = "phylotype"))
  expect_equal(hdata$n_samples, count(miseq, type = "sample"))
  expect_equal(dim(hdata$counts), c(63, 19))
  expect_equal(
    hdata$samples,
    strollur::names(miseq, type = "sample")
  )

  expect_equal(nrow(hdata$taxonomy), 63)
  expect_equal(ncol(hdata$taxonomy), 7)
  expect_equal(
    as.character(hdata$taxonomy[[62, "Phylum"]]),
    "\"Proteobacteria\""
  )
})
