# test "sequence_data"

test_that("test R6 sequence_data - intialize", {
  dataset <- sequence_data$new("mydata")

  expect_equal(dataset$get_dataset_name(), "mydata")

  dataset <- sequence_data$new(
    name = "soil",
    fasta = rdataset_example("test.fasta")
  )

  first_ten <- c(
    "M00967_43_000000000-A3JHG_1_1111_8697_7063",
    "M00967_43_000000000-A3JHG_1_1107_13334_19316",
    "M00967_43_000000000-A3JHG_1_2103_15942_24856",
    "M00967_43_000000000-A3JHG_1_2110_12430_18520",
    "M00967_43_000000000-A3JHG_1_1107_22778_21712",
    "M00967_43_000000000-A3JHG_1_1103_18837_8349",
    "M00967_43_000000000-A3JHG_1_1112_11891_19615",
    "M00967_43_000000000-A3JHG_1_1107_14687_22683",
    "M00967_43_000000000-A3JHG_1_1111_18897_11582",
    "M00967_43_000000000-A3JHG_1_1112_12027_22976"
  )

  expect_equal(first_ten, dataset$get_ids()[1:10])

  seq1 <- paste("TACGTAGGTGGCAAGCGTTATCCGGAATTATTGGGCGTAAAGAGCGCGCAGGTGGTTAATT",
    "AAGTCTGATGTGAAAGCCCACGGCTTAACCGTGGAGGGTCATTGGAAACTGGTTGACTTGA",
    "GTGCAGAAGAGGGAAGTGGAATTCCATGTGTAGCGGTGAAATGCGTAGAGATATGGAGGAA",
    "CACCAGTGGCGAAGGCGGCTTCCTGGTCTGCAACTGACACTGAGGCGCGAAAGCGTGGGGA",
    "GCAAACAGG",
    sep = "", collaspe = ""
  )
  seq2 <- paste("TACGGAGGATGCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGTGCGTAGGCGGGATGTC",
    "AAGTCAGCGGTAAAATTGTGGAGCTCAACTCCATCGAGCCGTTGAAACTGACGTTCTTGAG",
    "TGGGCGAGAAGTATGCGGAATGCGTGGTGTAGCGGTGAAATGCATAGATATCACGCAGAAC",
    "TCCGATTGCGAAGGCAGCATACCGGCGCCCTACTGACGCTGAAGCACGAAAGCGTGGGTAT",
    "CGAACAGG",
    sep = "", collaspe = ""
  )
  seq3 <- paste("TACGTAGGTGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGCGTGTAGGCGGGGACGC",
    "AAGTCAGATGTGAAAACCACGGGCTCAACCTGTGGCCTGCATTTGAAACTGTGTTTCTTGA",
    "GTACTGGAGAGGCAGACGGAATTCCTAGTGTAGCGGTGAAATGCGTAGATATTAGGAGGAA",
    "CACCAGTGGCGAAGGCGGTCTGCTGGACAGCAACTGACGCTGAGGCGCGAAAGCGTGGGGA",
    "GCAAACAGG",
    sep = "", collaspe = ""
  )
  seq4 <- paste("TACGTAGGGGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAGCGTAGACGGTGATGC",
    "AAGTCTGAAGTGAAAGGCGGGGGCTCAACCCCCGGACTGCTTTGGAAACTGTATGACTGGA",
    "GTGCAGGAGAGGTAAGTGGAATTCCTAGTGTAGCGGTGAAATGCGTAGATATTAGGAGGAA",
    "CACCAGTGGCGAAGGCGGCTTACTGGACTGTAACTGACGTTGAGGCTCGAAAGCGTGGGGA",
    "GCAAACAGG",
    sep = "", collaspe = ""
  )
  seq5 <- paste("TACGTAGGTGGCGAGCGTTGTCCGGATTTACTGGGCGTAAAGGGAGCGTAGGCGGACTTTT",
    "AAGTGAGATGTGAAATACTCGGGCTCAACTTGAGTGCTGCATTTCAAACTGGAAGTCTAGA",
    "GTGCAGGAGAGGAGAATGGAATTCCTAGTGTAGCGGTGAAATGCGTAGAGATTAGGAAGAA",
    "CACCAGTGGCGAAGGCGATTCTCTGGACTGTAACTGACGCTGAGGCTCGAAAGCGTGGGGA",
    "GCAAACAGG",
    sep = "", collaspe = ""
  )
  seq6 <- paste("TACGGAGGNTGGCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGTGCGTAGGCGGATCGG",
    "TTAAGTCAGTGGTCAAATTGAGGGGCTCAACCCCTTCCCGCCATTGAAACTGGCGATCTTG",
    "AGTGGAAGAGAAGTATGCGGAATGCGTGGTGTAGCGGTGAAATGCATAGATATCACGCAGA",
    "ACCCCGATTGCGAAGGCAGCATGCCGGCTTCCTACTGACGCTGAAGCACGAAAGCGTGGGT",
    "ATCGAACAGG",
    sep = "", collaspe = ""
  )
  seq7 <- paste("TACGGAGGATGCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGTGCGCAGGCGGAAGATC",
    "AAGTCAGCGGTAAAATTGAGAGGCTCAACCTCTTCGAGCCGTTGAAACTGGTTTTCTTGAG",
    "TGAGCGAGAAGTATGCGGAATGCGTGGTGTAGCGGTGAAATGCATAGATATCACGCAGAAC",
    "TCCGATTGCGAAGGCAGCATACCGGCGCTCAACTGACGCTCATGCACGAAAGTGTGGGTAT",
    "CGAACAGG",
    sep = "", collaspe = ""
  )
  seq8 <- paste("TACGGAGGATCCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGAGCGTAGGTGGATTGTT",
    "AAGTCAGTTGTGAAAGTTTGCGGCTCAACCGTAAAATTGCAGTTGAAACTGGCAGTCTTGA",
    "GTACAGTAGAGGTGGGCGGAATTCGTGGTGTAGCGGTGAAATGCTTAGATATCACGAAGAA",
    "CTCCGATTGCGAAGGCAGCTCACTGGACTGCAACTGACACTGATGCTCGAAAGTGTGGGTA",
    "TCAAACAGG",
    sep = "", collaspe = ""
  )
  seq9 <- paste("TACGTAGGGGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAGCGTAGACGGCCAGAC",
    "AAGTCTGAAGTGAAAATCCAGCGCTTAACGTTGGAAGTGCTTTGGAAACTGCCGGGCTAGA",
    "GTGCAGGAGGGGCAGGCGGAATTCCTAGTGTAGCGGTGAAATGCGTAGATATTAGGAGGAA",
    "CACCAGTGGCGAAGGCGGCCTGCTGGACTGCAACTGACGTTGAGGCTCGAAGGCGTGGGGA",
    "GCAAACAGG",
    sep = "", collaspe = ""
  )
  seq10 <- paste("TACGTAGGTGGCGAGCGTTGTCCGGATTTACTGGGCGTAAAGGGAGCGTAGGCGGACTTT",
    "TAAGTGAGATGTGAAATACTCGGGCTCAACTTGAGTGCTGCATTTCAAACTGGAAGTCTA",
    "GAGTGCAGGAGAGGAGAATGGAATTCCTAGTGTAGCGGTGAAATGCGTAGAGATTAGGAA",
    "GAACACCAGTGGCGAAGGCGATTCTCTGGACTGTAACTGACGCTGAGGCTCGAAAGCGTG",
    "GGGAGCAAACAGG",
    sep = "", collaspe = ""
  )

  first_ten_seqs <- c(
    seq1, seq2, seq3, seq4, seq5,
    seq6, seq7, seq8, seq9, seq10
  )

  expect_equal(first_ten_seqs, dataset$get_seqs()[1:10])
})
