// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/strollur.h"
#include <RcppThread.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// clear
Rcpp::Environment clear(Rcpp::Environment& data);
RcppExport SEXP _strollur_clear(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Environment& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(clear(data));
    return rcpp_result_gen;
END_RCPP
}
// get_bin_types
vector<string> get_bin_types(Rcpp::Environment data);
RcppExport SEXP _strollur_get_bin_types(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Environment >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(get_bin_types(data));
    return rcpp_result_gen;
END_RCPP
}
// has_sample
bool has_sample(Rcpp::Environment data, string sample);
RcppExport SEXP _strollur_has_sample(SEXP dataSEXP, SEXP sampleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Environment >::type data(dataSEXP);
    Rcpp::traits::input_parameter< string >::type sample(sampleSEXP);
    rcpp_result_gen = Rcpp::wrap(has_sample(data, sample));
    return rcpp_result_gen;
END_RCPP
}
// has_sequence_strings
bool has_sequence_strings(Rcpp::Environment data);
RcppExport SEXP _strollur_has_sequence_strings(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Environment >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(has_sequence_strings(data));
    return rcpp_result_gen;
END_RCPP
}
// is_aligned
bool is_aligned(Rcpp::Environment data);
RcppExport SEXP _strollur_is_aligned(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Environment >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(is_aligned(data));
    return rcpp_result_gen;
END_RCPP
}
// xdev_abundance
Rcpp::DataFrame xdev_abundance(const Rcpp::Environment& data, const string& type, const string& bin_type, bool by_sample);
RcppExport SEXP _strollur_xdev_abundance(SEXP dataSEXP, SEXP typeSEXP, SEXP bin_typeSEXP, SEXP by_sampleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::Environment& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const string& >::type type(typeSEXP);
    Rcpp::traits::input_parameter< const string& >::type bin_type(bin_typeSEXP);
    Rcpp::traits::input_parameter< bool >::type by_sample(by_sampleSEXP);
    rcpp_result_gen = Rcpp::wrap(xdev_abundance(data, type, bin_type, by_sample));
    return rcpp_result_gen;
END_RCPP
}
// xdev_add_references
Rcpp::Environment xdev_add_references(const Rcpp::Environment& data, const Rcpp::DataFrame& table, const string& name, const string& vendor, const string& version, const string& usage, const string& note, const string& method_url, const string& documentation_url, const string& parameter, const string& citation, bool verbose);
RcppExport SEXP _strollur_xdev_add_references(SEXP dataSEXP, SEXP tableSEXP, SEXP nameSEXP, SEXP vendorSEXP, SEXP versionSEXP, SEXP usageSEXP, SEXP noteSEXP, SEXP method_urlSEXP, SEXP documentation_urlSEXP, SEXP parameterSEXP, SEXP citationSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::Environment& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type table(tableSEXP);
    Rcpp::traits::input_parameter< const string& >::type name(nameSEXP);
    Rcpp::traits::input_parameter< const string& >::type vendor(vendorSEXP);
    Rcpp::traits::input_parameter< const string& >::type version(versionSEXP);
    Rcpp::traits::input_parameter< const string& >::type usage(usageSEXP);
    Rcpp::traits::input_parameter< const string& >::type note(noteSEXP);
    Rcpp::traits::input_parameter< const string& >::type method_url(method_urlSEXP);
    Rcpp::traits::input_parameter< const string& >::type documentation_url(documentation_urlSEXP);
    Rcpp::traits::input_parameter< const string& >::type parameter(parameterSEXP);
    Rcpp::traits::input_parameter< const string& >::type citation(citationSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(xdev_add_references(data, table, name, vendor, version, usage, note, method_url, documentation_url, parameter, citation, verbose));
    return rcpp_result_gen;
END_RCPP
}
// xdev_add_report
Rcpp::Environment xdev_add_report(const Rcpp::Environment& data, Rcpp::DataFrame table, const string& type, const string& sequence_name, bool verbose);
RcppExport SEXP _strollur_xdev_add_report(SEXP dataSEXP, SEXP tableSEXP, SEXP typeSEXP, SEXP sequence_nameSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::Environment& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type table(tableSEXP);
    Rcpp::traits::input_parameter< const string& >::type type(typeSEXP);
    Rcpp::traits::input_parameter< const string& >::type sequence_name(sequence_nameSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(xdev_add_report(data, table, type, sequence_name, verbose));
    return rcpp_result_gen;
END_RCPP
}
// xdev_add_sequences
Rcpp::Environment xdev_add_sequences(const Rcpp::Environment& data, const Rcpp::DataFrame& table, Rcpp::Nullable<Rcpp::List> reference, const string& sequence_name, const string& sequence, const string& comment, bool verbose);
RcppExport SEXP _strollur_xdev_add_sequences(SEXP dataSEXP, SEXP tableSEXP, SEXP referenceSEXP, SEXP sequence_nameSEXP, SEXP sequenceSEXP, SEXP commentSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::Environment& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type table(tableSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type reference(referenceSEXP);
    Rcpp::traits::input_parameter< const string& >::type sequence_name(sequence_nameSEXP);
    Rcpp::traits::input_parameter< const string& >::type sequence(sequenceSEXP);
    Rcpp::traits::input_parameter< const string& >::type comment(commentSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(xdev_add_sequences(data, table, reference, sequence_name, sequence, comment, verbose));
    return rcpp_result_gen;
END_RCPP
}
// xdev_assign_bins
Rcpp::Environment xdev_assign_bins(const Rcpp::Environment& data, const Rcpp::DataFrame& table, const string& bin_type, Rcpp::Nullable<Rcpp::List> reference, const string& bin_name, const string& abundance, const string& sample, const string& sequence_name, bool verbose);
RcppExport SEXP _strollur_xdev_assign_bins(SEXP dataSEXP, SEXP tableSEXP, SEXP bin_typeSEXP, SEXP referenceSEXP, SEXP bin_nameSEXP, SEXP abundanceSEXP, SEXP sampleSEXP, SEXP sequence_nameSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::Environment& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type table(tableSEXP);
    Rcpp::traits::input_parameter< const string& >::type bin_type(bin_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type reference(referenceSEXP);
    Rcpp::traits::input_parameter< const string& >::type bin_name(bin_nameSEXP);
    Rcpp::traits::input_parameter< const string& >::type abundance(abundanceSEXP);
    Rcpp::traits::input_parameter< const string& >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< const string& >::type sequence_name(sequence_nameSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(xdev_assign_bins(data, table, bin_type, reference, bin_name, abundance, sample, sequence_name, verbose));
    return rcpp_result_gen;
END_RCPP
}
// xdev_assign_bin_representative_sequences
Rcpp::Environment xdev_assign_bin_representative_sequences(const Rcpp::Environment& data, const Rcpp::DataFrame& table, const string& bin_type, Rcpp::Nullable<Rcpp::List> reference, const string& bin_name, const string& sequence_name, bool verbose);
RcppExport SEXP _strollur_xdev_assign_bin_representative_sequences(SEXP dataSEXP, SEXP tableSEXP, SEXP bin_typeSEXP, SEXP referenceSEXP, SEXP bin_nameSEXP, SEXP sequence_nameSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::Environment& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type table(tableSEXP);
    Rcpp::traits::input_parameter< const string& >::type bin_type(bin_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type reference(referenceSEXP);
    Rcpp::traits::input_parameter< const string& >::type bin_name(bin_nameSEXP);
    Rcpp::traits::input_parameter< const string& >::type sequence_name(sequence_nameSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(xdev_assign_bin_representative_sequences(data, table, bin_type, reference, bin_name, sequence_name, verbose));
    return rcpp_result_gen;
END_RCPP
}
// xdev_assign_bin_taxonomy
Rcpp::Environment xdev_assign_bin_taxonomy(const Rcpp::Environment& data, const Rcpp::DataFrame& table, const string& bin_type, Rcpp::Nullable<Rcpp::List> reference, const string& bin_name, const string& taxonomy, bool verbose);
RcppExport SEXP _strollur_xdev_assign_bin_taxonomy(SEXP dataSEXP, SEXP tableSEXP, SEXP bin_typeSEXP, SEXP referenceSEXP, SEXP bin_nameSEXP, SEXP taxonomySEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::Environment& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type table(tableSEXP);
    Rcpp::traits::input_parameter< const string& >::type bin_type(bin_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type reference(referenceSEXP);
    Rcpp::traits::input_parameter< const string& >::type bin_name(bin_nameSEXP);
    Rcpp::traits::input_parameter< const string& >::type taxonomy(taxonomySEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(xdev_assign_bin_taxonomy(data, table, bin_type, reference, bin_name, taxonomy, verbose));
    return rcpp_result_gen;
END_RCPP
}
// xdev_assign_sequence_taxonomy
Rcpp::Environment xdev_assign_sequence_taxonomy(const Rcpp::Environment& data, const Rcpp::DataFrame& table, Rcpp::Nullable<Rcpp::List> reference, const string& sequence_name, const string& taxonomy, bool verbose);
RcppExport SEXP _strollur_xdev_assign_sequence_taxonomy(SEXP dataSEXP, SEXP tableSEXP, SEXP referenceSEXP, SEXP sequence_nameSEXP, SEXP taxonomySEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::Environment& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type table(tableSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type reference(referenceSEXP);
    Rcpp::traits::input_parameter< const string& >::type sequence_name(sequence_nameSEXP);
    Rcpp::traits::input_parameter< const string& >::type taxonomy(taxonomySEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(xdev_assign_sequence_taxonomy(data, table, reference, sequence_name, taxonomy, verbose));
    return rcpp_result_gen;
END_RCPP
}
// xdev_assign_sequence_taxonomy_tidy
Rcpp::Environment xdev_assign_sequence_taxonomy_tidy(const Rcpp::Environment& data, const Rcpp::DataFrame& table, Rcpp::Nullable<Rcpp::List> reference, const string& sequence_name, const string& level, const string& taxonomy, const string& confidence, const bool verbose);
RcppExport SEXP _strollur_xdev_assign_sequence_taxonomy_tidy(SEXP dataSEXP, SEXP tableSEXP, SEXP referenceSEXP, SEXP sequence_nameSEXP, SEXP levelSEXP, SEXP taxonomySEXP, SEXP confidenceSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::Environment& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type table(tableSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type reference(referenceSEXP);
    Rcpp::traits::input_parameter< const string& >::type sequence_name(sequence_nameSEXP);
    Rcpp::traits::input_parameter< const string& >::type level(levelSEXP);
    Rcpp::traits::input_parameter< const string& >::type taxonomy(taxonomySEXP);
    Rcpp::traits::input_parameter< const string& >::type confidence(confidenceSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(xdev_assign_sequence_taxonomy_tidy(data, table, reference, sequence_name, level, taxonomy, confidence, verbose));
    return rcpp_result_gen;
END_RCPP
}
// xdev_assign_sequence_abundance
Rcpp::Environment xdev_assign_sequence_abundance(const Rcpp::Environment& data, const Rcpp::DataFrame& table, const string& sequence_name, const string& abundance, const string& sample, const string& treatment, bool verbose);
RcppExport SEXP _strollur_xdev_assign_sequence_abundance(SEXP dataSEXP, SEXP tableSEXP, SEXP sequence_nameSEXP, SEXP abundanceSEXP, SEXP sampleSEXP, SEXP treatmentSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::Environment& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type table(tableSEXP);
    Rcpp::traits::input_parameter< const string& >::type sequence_name(sequence_nameSEXP);
    Rcpp::traits::input_parameter< const string& >::type abundance(abundanceSEXP);
    Rcpp::traits::input_parameter< const string& >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< const string& >::type treatment(treatmentSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(xdev_assign_sequence_abundance(data, table, sequence_name, abundance, sample, treatment, verbose));
    return rcpp_result_gen;
END_RCPP
}
// xdev_assign_treatments
Rcpp::Environment xdev_assign_treatments(const Rcpp::Environment& data, const Rcpp::DataFrame& table, const string& sample, const string& treatment, bool verbose);
RcppExport SEXP _strollur_xdev_assign_treatments(SEXP dataSEXP, SEXP tableSEXP, SEXP sampleSEXP, SEXP treatmentSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::Environment& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type table(tableSEXP);
    Rcpp::traits::input_parameter< const string& >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< const string& >::type treatment(treatmentSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(xdev_assign_treatments(data, table, sample, treatment, verbose));
    return rcpp_result_gen;
END_RCPP
}
// xdev_count
double xdev_count(const Rcpp::Environment& data, const string& type, const string& bin_type, Rcpp::Nullable<Rcpp::List> samples, bool distinct);
RcppExport SEXP _strollur_xdev_count(SEXP dataSEXP, SEXP typeSEXP, SEXP bin_typeSEXP, SEXP samplesSEXP, SEXP distinctSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::Environment& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const string& >::type type(typeSEXP);
    Rcpp::traits::input_parameter< const string& >::type bin_type(bin_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< bool >::type distinct(distinctSEXP);
    rcpp_result_gen = Rcpp::wrap(xdev_count(data, type, bin_type, samples, distinct));
    return rcpp_result_gen;
END_RCPP
}
// xdev_export_dataset
/******************************************************************************/ Rcpp::List xdev_export_dataset(const Rcpp::Environment& data);
RcppExport SEXP _strollur_xdev_export_dataset(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::Environment& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(xdev_export_dataset(data));
    return rcpp_result_gen;
END_RCPP
}
// xdev_get_abundances_by_sample
vector<vector<float> > xdev_get_abundances_by_sample(const Rcpp::Environment& data, const Rcpp::CharacterVector& samples);
RcppExport SEXP _strollur_xdev_get_abundances_by_sample(SEXP dataSEXP, SEXP samplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::Environment& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type samples(samplesSEXP);
    rcpp_result_gen = Rcpp::wrap(xdev_get_abundances_by_sample(data, samples));
    return rcpp_result_gen;
END_RCPP
}
// xdev_get_list_vector
vector<string> xdev_get_list_vector(const Rcpp::Environment& data, const string& type);
RcppExport SEXP _strollur_xdev_get_list_vector(SEXP dataSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::Environment& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const string& >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(xdev_get_list_vector(data, type));
    return rcpp_result_gen;
END_RCPP
}
// xdev_get_by_sample
vector<vector<string> > xdev_get_by_sample(const Rcpp::Environment& data, const string& type, const Rcpp::CharacterVector& samples, bool degap);
RcppExport SEXP _strollur_xdev_get_by_sample(SEXP dataSEXP, SEXP typeSEXP, SEXP samplesSEXP, SEXP degapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::Environment& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const string& >::type type(typeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< bool >::type degap(degapSEXP);
    rcpp_result_gen = Rcpp::wrap(xdev_get_by_sample(data, type, samples, degap));
    return rcpp_result_gen;
END_RCPP
}
// xdev_get_sequences
vector<string> xdev_get_sequences(const Rcpp::Environment& data, const string& sample, bool degap);
RcppExport SEXP _strollur_xdev_get_sequences(SEXP dataSEXP, SEXP sampleSEXP, SEXP degapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::Environment& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const string& >::type sample(sampleSEXP);
    Rcpp::traits::input_parameter< bool >::type degap(degapSEXP);
    rcpp_result_gen = Rcpp::wrap(xdev_get_sequences(data, sample, degap));
    return rcpp_result_gen;
END_RCPP
}
// xdev_has_sequence_taxonomy
bool xdev_has_sequence_taxonomy(const Rcpp::Environment& data);
RcppExport SEXP _strollur_xdev_has_sequence_taxonomy(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::Environment& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(xdev_has_sequence_taxonomy(data));
    return rcpp_result_gen;
END_RCPP
}
// xdev_merge_bins
Rcpp::Environment xdev_merge_bins(const Rcpp::Environment& data, const vector<string>& bin_names, const string& reason, const string& bin_type);
RcppExport SEXP _strollur_xdev_merge_bins(SEXP dataSEXP, SEXP bin_namesSEXP, SEXP reasonSEXP, SEXP bin_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::Environment& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const vector<string>& >::type bin_names(bin_namesSEXP);
    Rcpp::traits::input_parameter< const string& >::type reason(reasonSEXP);
    Rcpp::traits::input_parameter< const string& >::type bin_type(bin_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(xdev_merge_bins(data, bin_names, reason, bin_type));
    return rcpp_result_gen;
END_RCPP
}
// xdev_merge_sequences
Rcpp::Environment xdev_merge_sequences(const Rcpp::Environment& data, const vector<string>& sequence_names, const string& reason);
RcppExport SEXP _strollur_xdev_merge_sequences(SEXP dataSEXP, SEXP sequence_namesSEXP, SEXP reasonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::Environment& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const vector<string>& >::type sequence_names(sequence_namesSEXP);
    Rcpp::traits::input_parameter< const string& >::type reason(reasonSEXP);
    rcpp_result_gen = Rcpp::wrap(xdev_merge_sequences(data, sequence_names, reason));
    return rcpp_result_gen;
END_RCPP
}
// xdev_names
vector<string> xdev_names(const Rcpp::Environment& data, const string& type, const string& bin_type, Rcpp::Nullable<Rcpp::List> samples, bool distinct);
RcppExport SEXP _strollur_xdev_names(SEXP dataSEXP, SEXP typeSEXP, SEXP bin_typeSEXP, SEXP samplesSEXP, SEXP distinctSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::Environment& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const string& >::type type(typeSEXP);
    Rcpp::traits::input_parameter< const string& >::type bin_type(bin_typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< bool >::type distinct(distinctSEXP);
    rcpp_result_gen = Rcpp::wrap(xdev_names(data, type, bin_type, samples, distinct));
    return rcpp_result_gen;
END_RCPP
}
// xdev_remove_bins
Rcpp::Environment xdev_remove_bins(const Rcpp::Environment& data, const vector<string>& bin_names, const vector<string>& trash_tags, const string& bin_type);
RcppExport SEXP _strollur_xdev_remove_bins(SEXP dataSEXP, SEXP bin_namesSEXP, SEXP trash_tagsSEXP, SEXP bin_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::Environment& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const vector<string>& >::type bin_names(bin_namesSEXP);
    Rcpp::traits::input_parameter< const vector<string>& >::type trash_tags(trash_tagsSEXP);
    Rcpp::traits::input_parameter< const string& >::type bin_type(bin_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(xdev_remove_bins(data, bin_names, trash_tags, bin_type));
    return rcpp_result_gen;
END_RCPP
}
// xdev_remove_lineages
Rcpp::Environment xdev_remove_lineages(const Rcpp::Environment& data, const vector<string>& contaminants, const string& reason);
RcppExport SEXP _strollur_xdev_remove_lineages(SEXP dataSEXP, SEXP contaminantsSEXP, SEXP reasonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::Environment& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const vector<string>& >::type contaminants(contaminantsSEXP);
    Rcpp::traits::input_parameter< const string& >::type reason(reasonSEXP);
    rcpp_result_gen = Rcpp::wrap(xdev_remove_lineages(data, contaminants, reason));
    return rcpp_result_gen;
END_RCPP
}
// xdev_remove_samples
Rcpp::Environment xdev_remove_samples(const Rcpp::Environment& data, const vector<string>& samples, const string& reason);
RcppExport SEXP _strollur_xdev_remove_samples(SEXP dataSEXP, SEXP samplesSEXP, SEXP reasonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::Environment& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const vector<string>& >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< const string& >::type reason(reasonSEXP);
    rcpp_result_gen = Rcpp::wrap(xdev_remove_samples(data, samples, reason));
    return rcpp_result_gen;
END_RCPP
}
// xdev_remove_sequences
Rcpp::Environment xdev_remove_sequences(const Rcpp::Environment& data, const vector<string>& sequence_names, const vector<string>& trash_tags);
RcppExport SEXP _strollur_xdev_remove_sequences(SEXP dataSEXP, SEXP sequence_namesSEXP, SEXP trash_tagsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::Environment& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const vector<string>& >::type sequence_names(sequence_namesSEXP);
    Rcpp::traits::input_parameter< const vector<string>& >::type trash_tags(trash_tagsSEXP);
    rcpp_result_gen = Rcpp::wrap(xdev_remove_sequences(data, sequence_names, trash_tags));
    return rcpp_result_gen;
END_RCPP
}
// xdev_report
Rcpp::DataFrame xdev_report(const Rcpp::Environment& data, const string& type, const string& bin_type);
RcppExport SEXP _strollur_xdev_report(SEXP dataSEXP, SEXP typeSEXP, SEXP bin_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::Environment& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const string& >::type type(typeSEXP);
    Rcpp::traits::input_parameter< const string& >::type bin_type(bin_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(xdev_report(data, type, bin_type));
    return rcpp_result_gen;
END_RCPP
}
// xdev_set_abundance
Rcpp::Environment xdev_set_abundance(const Rcpp::Environment& data, const vector<string>& sequence_names, const vector<float>& sequence_abundances, const string& reason);
RcppExport SEXP _strollur_xdev_set_abundance(SEXP dataSEXP, SEXP sequence_namesSEXP, SEXP sequence_abundancesSEXP, SEXP reasonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::Environment& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const vector<string>& >::type sequence_names(sequence_namesSEXP);
    Rcpp::traits::input_parameter< const vector<float>& >::type sequence_abundances(sequence_abundancesSEXP);
    Rcpp::traits::input_parameter< const string& >::type reason(reasonSEXP);
    rcpp_result_gen = Rcpp::wrap(xdev_set_abundance(data, sequence_names, sequence_abundances, reason));
    return rcpp_result_gen;
END_RCPP
}
// xdev_set_abundances
Rcpp::Environment xdev_set_abundances(const Rcpp::Environment& data, const vector<string>& sequence_names, const vector<vector<float>>& abundances, const string& reason);
RcppExport SEXP _strollur_xdev_set_abundances(SEXP dataSEXP, SEXP sequence_namesSEXP, SEXP abundancesSEXP, SEXP reasonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::Environment& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const vector<string>& >::type sequence_names(sequence_namesSEXP);
    Rcpp::traits::input_parameter< const vector<vector<float>>& >::type abundances(abundancesSEXP);
    Rcpp::traits::input_parameter< const string& >::type reason(reasonSEXP);
    rcpp_result_gen = Rcpp::wrap(xdev_set_abundances(data, sequence_names, abundances, reason));
    return rcpp_result_gen;
END_RCPP
}
// xdev_set_sequences
Rcpp::Environment xdev_set_sequences(const Rcpp::Environment& data, const vector<string>& sequence_names, const vector<string>& sequences, const Rcpp::CharacterVector& comments);
RcppExport SEXP _strollur_xdev_set_sequences(SEXP dataSEXP, SEXP sequence_namesSEXP, SEXP sequencesSEXP, SEXP commentsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::Environment& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const vector<string>& >::type sequence_names(sequence_namesSEXP);
    Rcpp::traits::input_parameter< const vector<string>& >::type sequences(sequencesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type comments(commentsSEXP);
    rcpp_result_gen = Rcpp::wrap(xdev_set_sequences(data, sequence_names, sequences, comments));
    return rcpp_result_gen;
END_RCPP
}
// xdev_set_dataset_name
void xdev_set_dataset_name(const Rcpp::Environment& data, const string& dataset_name);
RcppExport SEXP _strollur_xdev_set_dataset_name(SEXP dataSEXP, SEXP dataset_nameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::Environment& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const string& >::type dataset_name(dataset_nameSEXP);
    xdev_set_dataset_name(data, dataset_name);
    return R_NilValue;
END_RCPP
}
// xint_get_scrap_summary
Rcpp::DataFrame xint_get_scrap_summary(const Rcpp::Environment& data);
RcppExport SEXP _strollur_xint_get_scrap_summary(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::Environment& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(xint_get_scrap_summary(data));
    return rcpp_result_gen;
END_RCPP
}
// xint_copy_pointer
Rcpp::XPtr<Dataset> xint_copy_pointer(const Rcpp::Environment& data);
RcppExport SEXP _strollur_xint_copy_pointer(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::Environment& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(xint_copy_pointer(data));
    return rcpp_result_gen;
END_RCPP
}
// xint_new_pointer
Rcpp::XPtr<Dataset> xint_new_pointer(const string& dataset_name);
RcppExport SEXP _strollur_xint_new_pointer(SEXP dataset_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const string& >::type dataset_name(dataset_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(xint_new_pointer(dataset_name));
    return rcpp_result_gen;
END_RCPP
}
// xint_is_equal
bool xint_is_equal(Rcpp::Environment data, Rcpp::Environment data2);
RcppExport SEXP _strollur_xint_is_equal(SEXP dataSEXP, SEXP data2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Environment >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::Environment >::type data2(data2SEXP);
    rcpp_result_gen = Rcpp::wrap(xint_is_equal(data, data2));
    return rcpp_result_gen;
END_RCPP
}
// xint_deserialize_dobject
void xint_deserialize_dobject(Rcpp::Environment data);
RcppExport SEXP _strollur_xint_deserialize_dobject(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Environment >::type data(dataSEXP);
    xint_deserialize_dobject(data);
    return R_NilValue;
END_RCPP
}
// xint_serialize_dobject
Rcpp::RawVector xint_serialize_dobject(Rcpp::Environment data);
RcppExport SEXP _strollur_xint_serialize_dobject(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Environment >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(xint_serialize_dobject(data));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_strollur_clear", (DL_FUNC) &_strollur_clear, 1},
    {"_strollur_get_bin_types", (DL_FUNC) &_strollur_get_bin_types, 1},
    {"_strollur_has_sample", (DL_FUNC) &_strollur_has_sample, 2},
    {"_strollur_has_sequence_strings", (DL_FUNC) &_strollur_has_sequence_strings, 1},
    {"_strollur_is_aligned", (DL_FUNC) &_strollur_is_aligned, 1},
    {"_strollur_xdev_abundance", (DL_FUNC) &_strollur_xdev_abundance, 4},
    {"_strollur_xdev_add_references", (DL_FUNC) &_strollur_xdev_add_references, 12},
    {"_strollur_xdev_add_report", (DL_FUNC) &_strollur_xdev_add_report, 5},
    {"_strollur_xdev_add_sequences", (DL_FUNC) &_strollur_xdev_add_sequences, 7},
    {"_strollur_xdev_assign_bins", (DL_FUNC) &_strollur_xdev_assign_bins, 9},
    {"_strollur_xdev_assign_bin_representative_sequences", (DL_FUNC) &_strollur_xdev_assign_bin_representative_sequences, 7},
    {"_strollur_xdev_assign_bin_taxonomy", (DL_FUNC) &_strollur_xdev_assign_bin_taxonomy, 7},
    {"_strollur_xdev_assign_sequence_taxonomy", (DL_FUNC) &_strollur_xdev_assign_sequence_taxonomy, 6},
    {"_strollur_xdev_assign_sequence_taxonomy_tidy", (DL_FUNC) &_strollur_xdev_assign_sequence_taxonomy_tidy, 8},
    {"_strollur_xdev_assign_sequence_abundance", (DL_FUNC) &_strollur_xdev_assign_sequence_abundance, 7},
    {"_strollur_xdev_assign_treatments", (DL_FUNC) &_strollur_xdev_assign_treatments, 5},
    {"_strollur_xdev_count", (DL_FUNC) &_strollur_xdev_count, 5},
    {"_strollur_xdev_export_dataset", (DL_FUNC) &_strollur_xdev_export_dataset, 1},
    {"_strollur_xdev_get_abundances_by_sample", (DL_FUNC) &_strollur_xdev_get_abundances_by_sample, 2},
    {"_strollur_xdev_get_list_vector", (DL_FUNC) &_strollur_xdev_get_list_vector, 2},
    {"_strollur_xdev_get_by_sample", (DL_FUNC) &_strollur_xdev_get_by_sample, 4},
    {"_strollur_xdev_get_sequences", (DL_FUNC) &_strollur_xdev_get_sequences, 3},
    {"_strollur_xdev_has_sequence_taxonomy", (DL_FUNC) &_strollur_xdev_has_sequence_taxonomy, 1},
    {"_strollur_xdev_merge_bins", (DL_FUNC) &_strollur_xdev_merge_bins, 4},
    {"_strollur_xdev_merge_sequences", (DL_FUNC) &_strollur_xdev_merge_sequences, 3},
    {"_strollur_xdev_names", (DL_FUNC) &_strollur_xdev_names, 5},
    {"_strollur_xdev_remove_bins", (DL_FUNC) &_strollur_xdev_remove_bins, 4},
    {"_strollur_xdev_remove_lineages", (DL_FUNC) &_strollur_xdev_remove_lineages, 3},
    {"_strollur_xdev_remove_samples", (DL_FUNC) &_strollur_xdev_remove_samples, 3},
    {"_strollur_xdev_remove_sequences", (DL_FUNC) &_strollur_xdev_remove_sequences, 3},
    {"_strollur_xdev_report", (DL_FUNC) &_strollur_xdev_report, 3},
    {"_strollur_xdev_set_abundance", (DL_FUNC) &_strollur_xdev_set_abundance, 4},
    {"_strollur_xdev_set_abundances", (DL_FUNC) &_strollur_xdev_set_abundances, 4},
    {"_strollur_xdev_set_sequences", (DL_FUNC) &_strollur_xdev_set_sequences, 4},
    {"_strollur_xdev_set_dataset_name", (DL_FUNC) &_strollur_xdev_set_dataset_name, 2},
    {"_strollur_xint_get_scrap_summary", (DL_FUNC) &_strollur_xint_get_scrap_summary, 1},
    {"_strollur_xint_copy_pointer", (DL_FUNC) &_strollur_xint_copy_pointer, 1},
    {"_strollur_xint_new_pointer", (DL_FUNC) &_strollur_xint_new_pointer, 1},
    {"_strollur_xint_is_equal", (DL_FUNC) &_strollur_xint_is_equal, 2},
    {"_strollur_xint_deserialize_dobject", (DL_FUNC) &_strollur_xint_deserialize_dobject, 1},
    {"_strollur_xint_serialize_dobject", (DL_FUNC) &_strollur_xint_serialize_dobject, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_strollur(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
