# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name Rcpp_Dataset
#' @title Rcpp_Dataset
#' @description The 'Dataset' class is the backend C++ implementation of the R6
#' 'sequence_data' object. Along with the rcpp_module this class allows
#' package developers access to additional functionality. 'Dataset' stores
#' nucleotide sequences, abundance, sample and treatment assignments,
#' taxonomic classifications, asv / otu clusters. It creates various reports
#' and summaries. It is designed to facilitate data transfer and access across
#' multiple R packages.
#'
#' @seealso '?sequence_data'
#' @export
NULL

