# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name summarize_reports
#' @title summarize_reports
#' @rdname summarize_reports
#' @param report DataFrame, containing all numeric columns
#' @param count NumericalVector, containing abundances of sequences
#' @param processors Integer, number of cores to use. Default = all available
#' @description Summarizes a report
#' @return DataFrame with summary values
summarize_reports <- function(report, count, processors) {
    .Call(`_rdataset_summarize_reports`, report, count, processors)
}

