#' @importFrom stats setNames
#' @importFrom utils packageDescription
#' @importFrom utils packageVersion
#'
#' @title Write a \href{https://biom-format.org}{BIOM} formatted file containing
#'   your \href{https://mothur.org/strollur/reference/strollur.html}{strollur}
#'   objects data.
#' @description
#'
#' Write a \href{https://biom-format.org}{BIOM} formatted file containing your
#' strollur::strollur objects data.
#'
#' @param data a
#'   \href{https://mothur.org/strollur/reference/strollur.html}{strollur} object
#' @param file_root a string containing the root name of the output file.
#'   Default = `{dataset_name}`.`{bin_type}`.biom
#' @param path string containing the name of directory where the files
#' should be written. Default = current working directory.
#' @param taxonomy logical, when `TRUE` if consensus taxonomies are available
#'   include them in the biom file. Default = `TRUE`.
#' @param sequence logical, when `TRUE` if bins have a representative sequence
#'   or all bins contain a single feature sequence include the sequences in the
#'   biom file. Default = `TRUE`.
#'
#' @examples
#'
#' if (requireNamespace("h5lite", quietly = TRUE)) {
#'   miseq <- strollur::miseq_sop_example()
#'   strollur::write_biom(miseq, tempfile())
#' } else {
#'   message(paste(
#'     "To use this functionality you have to install the",
#'     "h5lite package."
#'   ))
#' }
#'
#' @return vector of BIOM file names. One for each bin type.
#' @export
write_biom <- function(data, file_root = NULL, path = NULL,
                       taxonomy = TRUE, sequence = TRUE) {
  if (!inherits(data, "strollur")) {
    stop("data must be a strollur object.")
  }

  if (is.null(file_root)) {
    file_root <- names(data, "dataset")
    if (file_root == "") {
      .abort_no_name()
    }
  }

  # if no path given, set to current working directory
  if (!is.null(path)) {
    if (!dir.exists(path)) {
      # create it
      dir.create(path)
    }
    file_root <- file.path(path, basename(file_root))
  } else {
    # if path = NULL and file_root does not include a path
    if (file_root == basename(file_root)) {
      file_root <- file.path(getwd(), basename(file_root))
    }
  }

  bin_types <- data$get_bin_types()
  sample_names <- xdev_names(data, type = "sample")

  pkg_name <- "strollur"
  pkg_version <- as.character(packageVersion(pkg_name))
  pkg_author <- packageDescription(pkg_name, fields = "Maintainer")
  pkg_url <- packageDescription(pkg_name, fields = "URL")

  package_info <- paste0(
    "Generated by: ", pkg_name, " (v", pkg_version, ")\n",
    "Maintainer: ", pkg_author, "\n",
    "Source: ", ifelse(is.na(pkg_url), "No URL listed", pkg_url)
  )


  outputs <- c()

  if (length(bin_types) != 0) {
    for (type in bin_types) {
      num_bins <- xdev_count(data, type = "bin", bin_type = type)
      bin_names <- xdev_names(data, type = "bin", bin_type = type)
      bin_abundance_by_sample <- xdev_get_bin_abundances_by_sample(
        data,
        type
      )
      # bin abundance
      counts_matrix <- matrix(
        unlist(bin_abundance_by_sample),
        nrow = num_bins,
        byrow = TRUE,
        dimnames = list(bin_names, sample_names)
      )

      # sample / treatment metadata
      sample_metadata <- data.frame(
        row.names = xdev_names(data, type = "sample"),
        Treatment = xdev_report(data, type = "sample_assignment")
      )

      if (taxonomy) {
        con_tax <- xdev_report(data,
          type = "bin_taxonomy",
          bin_type = type
        )
        if (nrow(con_tax) != 0) {
          taxonomy_matrix <- matrix(con_tax$taxonomy,
            nrow = num_bins,
            byrow = TRUE,
            dimnames = list(bin_names, unique(con_tax$level))
          )

          biom_obj <- rbiom::as_rbiom(
            biom     = counts_matrix,
            metadata = sample_metadata,
            taxonomy = taxonomy_matrix,
          )
        }
      } else {
        biom_obj <- rbiom::as_rbiom(
          biom     = counts_matrix,
          metadata = sample_metadata
        )
      }

      if (sequence) {
        # check for bin_representatives, or alternatively
        # if bin names match sequence names use them
        reps <- xdev_report(data,
          type = "bin_representative",
          bin_type = type
        )

        if (nrow(reps) != 0) {
          biom_obj$sequences <- setNames(
            reps$representative_sequence,
            bin_names
          )
        } else if (count(data, type = "sequence",
                         distinct = TRUE) == num_bins) {
          # same number of sequences as bins
          biom_obj$sequences <- setNames(
            xdev_get_sequences(data),
            bin_names
          )
        }
      }
      biom_obj$id <- xdev_names(data, type = "dataset")
      biom_obj$comment <- package_info
      biom_obj$date <- format(Sys.time(), "%Y-%m-%dT%H:%M:%SZ")

      output_file <- paste0(file_root, ".", type, ".biom")

      if (file.exists(output_file)) {
        file.remove(output_file)
      }

      rbiom::write_biom(
        biom = biom_obj,
        file = output_file,
        format = "hdf5"
      )
      outputs <- c(outputs, output_file)
    }
    return(outputs)
  }
  "no_biom_data"
}
